replicaCount: 3

nginx:
  name: nginx-proxy
  namespace: nginx-proxy
  image: saravana227/nginx_proxy_k8s:latest
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30080

ingressController:
  namespace: ingress-nginx
  name: ingress-nginx-controller
  image: k8s.gcr.io/ingress-nginx/controller:v1.10.1
  replicas: 1
  service:
    type: NodePort
    httpPort: 80
    httpsPort: 443
    httpNodePort: 30080
    httpsNodePort: 30443

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: myapp.local  # Change to your domain or AWS LB DNS
      paths:
        - path: /
          pathType: Prefix
  tls: []   # Example:
  # tls:
  #   - hosts:
  #       - myapp.local
  #     secretName: myapp-tls
