---
replicaCount: 1

frontend:
  name: frontend
  namespace: frontend
  image: saravana227/frontend:latest
  service:
    name: frontend
    type: ClusterIP
    port: 80
    targetPort: 5000
  env:
    backendUrl: http://backend.backend.svc.cluster.local:5000
  secret:
    name: frontend-secret
    values:
      user: bXl1c2Vy
      password: bXlwYXNzd29yZA==
      database: bXlkYg==
    user:
      key: user
    password:
      key: password
    database:
      key: database
