# Global settings
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

imagePullSecrets: []

# Custom ServiceAccount settings
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

# Frontend config
frontend:
  name: frontend
  namespace: frontend
  image: saravana227/frontend:latest
  secret:
    name: mysql-secret
  service:
    name: frontend
    type: NodePort
    port: 80
    targetPort: 5000
    nodePort: 30080
  env:
    backendUrl: http://backend.backend.svc.cluster.local:5001

# Backend config
backend:
  name: backend
  namespace: backend
  image: saravana227/backend:latest
  secret:
    name: mysql-secret
    user:
      key: user
    password:
      key: password
    database:
      key: database
  service:
    name: backend
    type: ClusterIP
    port: 5000
    targetPort: 5001
  env:
    mysqlHost: mysql.mysql.svc.cluster.local

# MySQL config
mysql:
  name: mysql
  namespace: mysql
  image: mysql:5.7
  secret:
    name: mysql-secret
    values:
      user: bXl1c2Vy
      password: bXlwYXNzd29yZA==
      database: bXlkYg==
    user:
      key: user
    password:
      key: password
    database:
      key: database
  service:
    name: mysql
    port: 3306
  storage:
    storage: 1Gi
    path: /mnt/mysql-data
    mountPath: /var/lib/mysql
    pv:
      name: mysql-pv
    pvc:
      name: mysql-pvc
  volumeMounts:
    name: mysql-pv

# Autoscaling (used in HPA)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Ingress - disabled (you are using NodePort for frontend)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
