---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.frontend.namespace }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.backend.namespace }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.mysql.namespace }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nginx.namespace }}
