apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: three-tier-app
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-07-22T20:49:50Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: frontend
  namespace: frontend
  resourceVersion: "3724"
  uid: 2fc73fa7-cfb0-47b1-9ea8-a5282b5def19
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: saravana227/frontend:latest
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-22T20:49:53Z"
    lastUpdateTime: "2025-07-22T20:49:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-22T20:49:50Z"
    lastUpdateTime: "2025-07-22T20:49:53Z"
    message: ReplicaSet "frontend-7999895897" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
