apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ingressController.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ingressController.name }}
  namespace: {{ .Values.ingressController.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingressController.name }}
  namespace: {{ .Values.ingressController.namespace }}
spec:
  type: {{ .Values.ingressController.service.type }}
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: {{ .Values.ingressController.service.httpPort }}
      targetPort: http
      nodePort: {{ .Values.ingressController.service.httpNodePort }}
    - name: https
      port: {{ .Values.ingressController.service.httpsPort }}
      targetPort: https
      nodePort: {{ .Values.ingressController.service.httpsNodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ingressController.name }}
  namespace: {{ .Values.ingressController.namespace }}
spec:
  replicas: {{ .Values.ingressController.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ .Values.ingressController.name }}
      containers:
        - name: controller
          image: {{ .Values.ingressController.image }}
          args:
            - /nginx-ingress-controller
            - --publish-service=$(POD_NAMESPACE)/{{ .Values.ingressController.name }}
            - --election-id=ingress-controller-leader
            - --controller-class=k8s.io/ingress-nginx
            - --ingress-class={{ .Values.ingress.className }}
            - --configmap=$(POD_NAMESPACE)/{{ .Values.ingressController.name }}
          ports:
            - name: http
              containerPort: {{ .Values.ingressController.service.httpPort }}
            - name: https
              containerPort: {{ .Values.ingressController.service.httpsPort }}
