apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.ingressController.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/component: controller
    spec:
      containers:
      - name: controller
        image: {{ .Values.ingressController.image | default "k8s.gcr.io/ingress-nginx/controller:v1.10.1" }}
        args:
          - /nginx-ingress-controller
          - --publish-service=$(POD_NAMESPACE)/ingress-nginx-controller
          - --election-id=ingress-controller-leader
          - --controller-class=k8s.io/ingress-nginx
          - --ingress-class=nginx
          - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.ingressController.service.httpPort | default 80 }}
      targetPort: 80
      nodePort: {{ .Values.ingressController.service.httpNodePort | default 30080 }}
    - name: https
      port: {{ .Values.ingressController.service.httpsPort | default 443 }}
      targetPort: 443
      nodePort: {{ .Values.ingressController.service.httpsNodePort | default 30443 }}
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
