replicaCount: 2
mysql:
  name: mysql
  namespace: mysql
  image: mysql:5.7
  secret:
    name: mysql-secret
    values:
      user: bXl1c2Vy
      password: bXlwYXNzd29yZA==
      database: bXlkYg==
    user:
      key: user
    password:
      key: password
    database:
      key: database
  service:
    name: mysql
    port: 3306
  storage:
    storage: 1Gi
    path: /mnt/mysql-data
    mountPath: /var/lib/mysql
    pv:
      name: mysql-pv
    pvc:
      name: mysql-pvc
  volumeMounts:
    name: mysql-pv
